version: "3.8"
services:
  angular:
    build: .
    volumes: 
      - .:/usr/src/app
    ports: 
      - 4200:4200
    env_file:
      - .env
    environment:
      SONAR_LOGIN_KEY: ${SONAR_LOGIN_KEY}
      SONAR_PROJECT_KEY: ${SONAR_PROJECT_KEY}
      PERSONAL_NAME: ${PERSONAL_NAME}