name: Node CI/CD

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm ci
      - run: npm test
      - run: npm run build
  firebase-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: "17.x"
      - uses: npm ci
      - uses: npm run build
      - uses: w9jds/firebase-action@main
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{FIREBASE_API_KEY}}
